import { Doctor, Test } from './types';

export const DOCTORS_DATA: Doctor[] = [
  {
    id: "dr-nur-islam",
    nameBD: "অধ্যাপক ডা. মোঃ নূর-ইসলাম",
    nameEN: "Prof. Dr. Md. Nur-Islam",
    titleBD: "মেডিসিন বিশেষজ্ঞ",
    titleEN: "Medicine Specialist",
    qualificationsBD: "এমবিবিএস, এমফিল, এফসিপিএস (মেডিসিন)",
    qualificationsEN: "MBBS, MPhil, FCPS (Medicine)",
    designationBD: "অধ্যাপক ও বিভাগীয় প্রধান (মেডিসিন বিভাগ) এবং অধ্যক্ষ, প্রাইম মেডিকেল কলেজ ও হাসপাতাল, রংপুর",
    designationEN: "Professor & HOD (Medicine) & Principal, Prime Medical College & Hospital, Rangpur",
    scheduleBD: "প্রতি শুক্রবার: সকাল ১১:০০টা – সন্ধ্যা ৭:০০টা",
    scheduleEN: "Every Friday: 11:00 AM – 07:00 PM",
    daysBD: ["শুক্রবার"],
    daysEN: ["Friday"],
    categories: ["medicine"],
    phoneSerials: ["01717-975461", "01705-485643"],
    image: "/input_file_0.png",
    chamberBD: "নিরাময় ক্লিনিক এন্ড ডায়াগনোসিস, বিডিআর রোড, লালমনিরহাট",
    chamberEN: "Niramoy Clinic & Diagnosis, BDR Road, Lalmonirhat"
  },
  {
    id: "dr-shariful-nontu",
    nameBD: "ডা. মোঃ শরীফুল ইসলাম (ননতু)",
    nameEN: "Dr. Md. Shariful Islam (Nontu)",
    titleBD: "জেনারেল, ল্যাপারোস্কপিক ও কলোরেক্টাল সার্জারী বিশেষজ্ঞ",
    titleEN: "General, Laparoscopic & Colorectal Surgeon",
    qualificationsBD: "এমবিবিএস, বিসিএস (স্বাস্থ্য), এমএস (জেনারেল সার্জারী), নিউরো সার্জারীতে উচ্চতর প্রশিক্ষণপ্রাপ্ত",
    qualificationsEN: "MBBS, BCS (Health), MS (General Surgery), Advanced Training in Neurosurgery",
    designationBD: "সহকারী অধ্যাপক (সার্জারী), রংপুর মেডিকেল কলেজ হাসপাতাল, রংপুর",
    designationEN: "Assistant Professor (Surgery), Rangpur Medical College Hospital, Rangpur",
    scheduleBD: "প্রতি শুক্রবার: সকাল ১০:০০টা – রাত ৮:০০টা",
    scheduleEN: "Every Friday: 10:00 AM – 08:00 PM",
    daysBD: ["শুক্রবার"],
    daysEN: ["Friday"],
    categories: ["surgery"],
    phoneSerials: ["01717-975461", "01705-485643"],
    image: "/input_file_1.png",
    specialtiesBD: ["পিত্তথলী ও পিত্তনালীর সার্জারী", "লেজার সার্জারী", "পাকস্থলীর সার্জারী", "ব্রেস্ট ও স্তনের সার্জারী", "পাইলস ও ফিস্টুলার লেজার সার্জারী", "ক্যান্সার সার্জারী"],
    specialtiesEN: ["Gallbladder & Bile Duct Surgery", "Laser Surgery", "Stomach Surgery", "Breast Surgery", "Piles & Fistula Laser Surgery", "Oncology (Cancer) Surgery"],
    chamberBD: "নিরাময় ক্লিনিক এন্ড ডায়াগনোসিস, বিডিআর রোড, লালমনিরহাট",
    chamberEN: "Niramoy Clinic & Diagnosis, BDR Road, Lalmonirhat"
  },
  {
    id: "dr-nurnabi-ansari",
    nameBD: "ডা. মোঃ নূরনবী আনছারী",
    nameEN: "Dr. Md. Nurnabi Ansari",
    titleBD: "নাক, কান, গলা রোগ বিশেষজ্ঞ ও হেড-নেক সার্জন",
    titleEN: "ENT Specialist & Head-Neck Surgeon",
    qualificationsBD: "এমবিবিএস, বিসিএস (স্বাস্থ্য), ডিএলও (ইএনটি)",
    qualificationsEN: "MBBS, BCS (Health), DLO (ENT)",
    designationBD: "নাক, কান, গলা ও হেড-নেক সার্জারি বিভাগ, রংপুর মেডিকেল কলেজ ও হাসপাতাল, রংপুর",
    designationEN: "Department of ENT & Head-Neck Surgery, Rangpur Medical College & Hospital, Rangpur",
    scheduleBD: "প্রতি রবি ও মঙ্গলবার: বিকাল ৩:০০টা – রাত ৮:০০টা",
    scheduleEN: "Every Sunday & Tuesday: 03:00 PM – 08:00 PM",
    daysBD: ["রবিবার", "মঙ্গলবার"],
    daysEN: ["Sunday", "Tuesday"],
    categories: ["ent"],
    phoneSerials: ["01717-975461", "01705-485643"],
    image: "/input_file_2.png",
    chamberBD: "নিরাময় ক্লিনিক এন্ড ডায়াগনোসিস, বিডিআর রোড, লালমনিরহাট",
    chamberEN: "Niramoy Clinic & Diagnosis, BDR Road, Lalmonirhat"
  },
  {
    id: "dr-ahad-box",
    nameBD: "ডা. আহাদ বক্স",
    nameEN: "Dr. Ahad Box",
    titleBD: "মেডিসিন ও উপ-বিশেষজ্ঞ (ডায়াবেটিস, বাতব্যথা ও চর্ম)",
    titleEN: "Medicine, Diabetes & Rheumatology Specialist",
    qualificationsBD: "এমবিবিএস, বিসিএস (স্বাস্থ্য), সিসিডি (বারডেম), এফসিপিএস (মেডিসিন)",
    qualificationsEN: "MBBS, BCS (Health), CCD (BIRDEM), FCPS (Medicine)",
    designationBD: "কনসালটেন্ট, মেডিসিন বিভাগ, রংপুর মেডিকেল কলেজ হাসপাতাল, রংপুর",
    designationEN: "Consultant, Department of Medicine, Rangpur Medical College Hospital, Rangpur",
    scheduleBD: "প্রতি মঙ্গলবার: বিকাল ৩:০০টা – রাত ৮:০০টা",
    scheduleEN: "Every Tuesday: 03:00 PM – 08:00 PM",
    daysBD: ["মঙ্গলবার"],
    daysEN: ["Tuesday"],
    categories: ["medicine"],
    phoneSerials: ["01717-975461", "01705-485643"],
    image: "/input_file_3.png",
    specialtiesBD: ["ডায়াবেটিস", "বাত ব্যথা রোগ", "এ্যাজমা ও হাঁপানী", "চর্ম ও এলার্জি রোগ"],
    specialtiesEN: ["Diabetes Management", "Rheumatism & Joint Pain", "Asthma & Respiratory Allergy", "Skin & Allergy Pathologies"],
    chamberBD: "নিরাময় ক্লিনিক এন্ড ডায়াগনোসিস, বিডিআর রোড, লালমনিরহাট",
    chamberEN: "Niramoy Clinic & Diagnosis, BDR Road, Lalmonirhat"
  },
  {
    id: "dr-novera-islam",
    nameBD: "ডা. নভেরা ইসলাম",
    nameEN: "Dr. Novera Islam",
    titleBD: "প্রসূতি ও স্ত্রীরোগ বিশেষজ্ঞ এবং সার্জন",
    titleEN: "Gynecology & Obstetrics Specialist & Surgeon",
    qualificationsBD: "এমবিবিএস, বিসিএস (স্বাস্থ্য), এফসিপিএস (অবস্ এন্ড গাইনী)",
    qualificationsEN: "MBBS, BCS (Health), FCPS (Obs & Gynae)",
    designationBD: "কনসালটেন্ট (গাইনী বিভাগ), রংপুর মেডিকেল কলেজ ও হাসপাতাল, রংপুর",
    designationEN: "Consultant (Gynecology), Rangpur Medical College & Hospital, Rangpur",
    scheduleBD: "প্রতি মঙ্গলবার ও বৃহস্পতিবার: বিকাল ৩:০০টা – রাত ৮:০০টা",
    scheduleEN: "Every Tuesday & Thursday: 03:00 PM – 08:00 PM",
    daysBD: ["মঙ্গলবার", "বৃহস্পতিবার"],
    daysEN: ["Tuesday", "Thursday"],
    categories: ["gynecology"],
    phoneSerials: ["01723-464440", "01705-485643"],
    image: "/input_file_4.png",
    chamberBD: "নিরাময় ক্লিনিক এন্ড ডায়াগনোসিস, বিডিআর রোড, লালমনিরহাট",
    chamberEN: "Niramoy Clinic & Diagnosis, BDR Road, Lalmonirhat"
  },
  {
    id: "dr-israt-jahan-lopa",
    nameBD: "ডা. ইসরাত জাহান (লোপা)",
    nameEN: "Dr. Israt Jahan (Lopa)",
    titleBD: "স্ত্রীরোগ ও বন্ধ্যাত্ব বিশেষজ্ঞ এবং সার্জন",
    titleEN: "Gynecology, Obstetrics & Infertility Specialist",
    qualificationsBD: "এমবিবিএস, বিসিএস (স্বাস্থ্য), ইওসি, এফসিপিএস (অবস্ এন্ড গাইনী)",
    qualificationsEN: "MBBS, BCS (Health), EOC, FCPS (Obs & Gynae)",
    designationBD: "বন্ধ্যাত্ব বিষয়ে বিশেষ প্রশিক্ষণপ্রাপ্ত (মুম্বাই, ইন্ডিয়া), কনসালটেন্ট, প্রসূতি ও স্ত্রীরোগ",
    designationEN: "Fertility Specialist (Infertility Training, Mumbai, India), Consultant, Obs & Gynae",
    scheduleBD: "প্রতি বুধবার: বিকাল ৩:০০টা – রাত ৯:০০টা",
    scheduleEN: "Every Wednesday: 03:00 PM – 09:00 PM",
    daysBD: ["বুধবার"],
    daysEN: ["Wednesday"],
    categories: ["gynecology"],
    phoneSerials: ["01723-464440", "01717-975461"],
    image: "/input_file_5.png",
    chamberBD: "নিরাময় ক্লিনিক এন্ড ডায়াগনোসিস, বিডিআর রোড, লালমনিরহাট",
    chamberEN: "Niramoy Clinic & Diagnosis, BDR Road, Lalmonirhat"
  },
  {
    id: "dr-mm-haq-mahfil",
    nameBD: "সহযোগী অধ্যাপক ডা. এম.এম. হক (মাহফিল)",
    nameEN: "Assoc. Prof. Dr. M.M. Haq (Mahfil)",
    titleBD: "হাড়-জোড়, বাত ব্যথা, ট্রমা বিশেষজ্ঞ ও সার্জন",
    titleEN: "Orthopedics, Joint Pain, Trauma Specialist & Surgeon",
    qualificationsBD: "এমবিবিএস, বিসিএস (স্বাস্থ্য), এমএস (অর্থো-সার্জারী)",
    qualificationsEN: "MBBS, BCS (Health), MS (Ortho-Surgery)",
    designationBD: "সহকারী/সহযোগী অধ্যাপক, রংপুর মেডিকেল কলেজ ও হাসপাতাল, রংপুর",
    designationEN: "Assistant/Associate Professor, Rangpur Medical College & Hospital, Rangpur",
    scheduleBD: "প্রতি সোমবার: দুপুর ৩:০০টা – রাত ৮:০০টা",
    scheduleEN: "Every Monday: 03:00 PM – 08:00 PM",
    daysBD: ["সোমবার"],
    daysEN: ["Monday"],
    categories: ["orthopedics"],
    phoneSerials: ["01723-464440", "01705-485643"],
    image: "/input_file_6.png",
    chamberBD: "নিরাময় ক্লিনিক এন্ড ডায়াগনোসিস, বিডিআর রোড, লালমনিরহাট",
    chamberEN: "Niramoy Clinic & Diagnosis, BDR Road, Lalmonirhat"
  },
  {
    id: "dr-abdul-jabbar",
    nameBD: "ডা. মোঃ আব্দুল জব্বার",
    nameEN: "Dr. Md. Abdul Jabbar",
    titleBD: "জেনারেল, ল্যাপারোস্কপিক ও কলোরেক্টাল সার্জন",
    titleEN: "General, Laparoscopic & Colorectal Surgeon",
    qualificationsBD: "এমবিবিএস, এফসিপিএস (সার্জারী), এফসিপিএস (কলোরেক্টাল সার্জন কোর্স)",
    qualificationsEN: "MBBS, FCPS (Surgery), FCPS (Colorectal Surgeon Course)",
    designationBD: "সার্জারী বিশেষজ্ঞ, শহীদ সোহরাওয়ার্দী মেডিকেল কলেজ ও হাসপাতাল, ঢাকা",
    designationEN: "Surgery Specialist, Shaheed Suhrawardy Medical College, Dhaka",
    scheduleBD: "প্রতি শুক্রবার: সকাল ১১:০০টা – রাত ৮:০০টা",
    scheduleEN: "Every Friday: 11:00 AM – 08:00 PM",
    daysBD: ["শুক্রবার"],
    daysEN: ["Friday"],
    categories: ["surgery"],
    phoneSerials: ["01723-464440", "01705-485643"],
    image: "/input_file_7.png",
    chamberBD: "নিরাময় ক্লিনিক এন্ড ডায়াগনোসিস, বিডিআর রোড, লালমনিরহাট",
    chamberEN: "Niramoy Clinic & Diagnosis, BDR Road, Lalmonirhat"
  },
  {
    id: "dr-mithun-barman",
    nameBD: "ডা. মিঠুন কুমার বর্মণ",
    nameEN: "Dr. Mithun Kumar Barman",
    titleBD: "মেডিসিন, হৃদরোগ ও ডায়াবেটিস বিশেষজ্ঞ",
    titleEN: "Medicine, Cardiology & Diabetes Specialist",
    qualificationsBD: "এমবিবিএস, মেডিসিন ও কার্ডিওলজি বিশেষ প্রশিক্ষণপ্রাপ্ত",
    qualificationsEN: "MBBS, Advanced Training in Medicine & Cardiology",
    designationBD: "রেজিস্ট্রার / বিশেষজ্ঞ চিকিৎসক, নিরাময় ক্লিনিক",
    designationEN: "Resident Specialist, Niramoy Clinic",
    scheduleBD: "প্রতি শনিবার: দুপুর ২:৩০টা – রাত ৮:০০টা",
    scheduleEN: "Every Saturday: 02:30 PM – 08:00 PM",
    daysBD: ["শনিবার"],
    daysEN: ["Saturday"],
    categories: ["medicine"],
    phoneSerials: ["01717-975461", "01705-485643"],
    image: "placeholder",
    chamberBD: "নিরাময় ক্লিনিক এন্ড ডায়াগনোসিস, বিডিআর রোড, লালমনিরহাট",
    chamberEN: "Niramoy Clinic & Diagnosis, BDR Road, Lalmonirhat"
  },
  {
    id: "dr-iffat-eva",
    nameBD: "ডা. ইফফাত জাহান আব্দুল্লাহ (ইভা)",
    nameEN: "Dr. Iffat Jahan Abdullah (Eva)",
    titleBD: "গাইনী ও অবস বিশেষজ্ঞ এবং সার্জন",
    titleEN: "Gynecology & Obstetrics Specialist & Surgeon",
    qualificationsBD: "এমবিবিএস, এফসিপিএস (গাইনী ও অবস)",
    qualificationsEN: "MBBS, FCPS (Gynae & Obs)",
    designationBD: "স্ত্রীরোগ ও প্রসূতি সার্জন, নিরাময় ক্লিনিক",
    designationEN: "Gynecological & Pregnancy Surgeon, Niramoy Clinic",
    scheduleBD: "প্রতি শুক্রবার: বিকাল ৩:০০টা – রাত ৮:০০টা",
    scheduleEN: "Every Friday: 03:00 PM – 08:00 PM",
    daysBD: ["শুক্রবার"],
    daysEN: ["Friday"],
    categories: ["gynecology"],
    phoneSerials: ["01717-975461", "01705-485643"],
    image: "placeholder",
    chamberBD: "নিরাময় ক্লিনিক এন্ড ডায়াগনোসিস, বিডিআর রোড, লালমনিরহাট",
    chamberEN: "Niramoy Clinic & Diagnosis, BDR Road, Lalmonirhat"
  },
  {
    id: "dr-nahid-badsha",
    nameBD: "ডা. মোঃ নাহিদ বাদশা",
    nameEN: "Dr. Md. Nahid Badsha",
    titleBD: "অর্থোপেডিক্স বিশেষজ্ঞ ও ট্রমা সার্জন",
    titleEN: "Orthopedics & Joint Trauma Specialist",
    qualificationsBD: "এমবিবিএস, অর্থোপেডিক সার্জারিতে উচ্চতর প্রশিক্ষণ",
    qualificationsEN: "MBBS, Advanced Training in Orthopedic Surgery",
    designationBD: "হাড়-জোড় ও পঙ্গু রোগ বিশেষজ্ঞ সার্জন",
    designationEN: "Bone, Joint & Trauma Specialist Surgeon",
    scheduleBD: "প্রতি রবি ও বুধবার: দুপুর ২:৩০টা – রাত ৮:০০টা",
    scheduleEN: "Every Sunday & Wednesday: 02:30 PM – 08:00 PM",
    daysBD: ["রবিবার", "বুধবার"],
    daysEN: ["Sunday", "Wednesday"],
    categories: ["orthopedics"],
    phoneSerials: ["01717-975461", "01705-485643"],
    image: "placeholder",
    chamberBD: "নিরাময় ক্লিনিক এন্ড ডায়াগনোসিস, বিডিআর রোড, লালমনিরহাট",
    chamberEN: "Niramoy Clinic & Diagnosis, BDR Road, Lalmonirhat"
  },
  {
    id: "dr-zinia-afrin",
    nameBD: "ডা. মোসাঃ জিনিয়া আফরিন",
    nameEN: "Dr. Mosammat Zinia Afrin",
    titleBD: "গাইনী ও অবস বিশেষজ্ঞ এবং সার্জন",
    titleEN: "Gynecology & Obstetrics Consultant",
    qualificationsBD: "এমবিবিএস, বিশেষ ইওসি প্রশিণপ্রাপ্ত ও গাইনী বিশেষজ্ঞ",
    qualificationsEN: "MBBS, EOC Trained, Gynecological Surgery Specialist",
    designationBD: "কনসালটেন্ট, প্রসূতি ও স্ত্রীরোগ বিভাগ, নিরাময় ক্লিনিক",
    designationEN: "Consultant Gynecology & Maternity Services, Niramoy Clinic",
    scheduleBD: "প্রতি রবিবার: বিকাল ৩:০০টা – রাত ৯:০০টা",
    scheduleEN: "Every Sunday: 03:00 PM – 09:00 PM",
    daysBD: ["রবিবার"],
    daysEN: ["Sunday"],
    categories: ["gynecology"],
    phoneSerials: ["01717-975461", "01705-485643"],
    image: "placeholder",
    chamberBD: "নিরাময় ক্লিনিক এন্ড ডায়াগনোসিস, বিডিআর রোড, লালমনিরহাট",
    chamberEN: "Niramoy Clinic & Diagnosis, BDR Road, Lalmonirhat"
  },
  {
    id: "dr-rebeka-rupa",
    nameBD: "ডা. রেবেকা আখতার (রূপা)",
    nameEN: "Dr. Rebeka Akter (Rupa)",
    titleBD: "গাইনী ও অবস বিশেষজ্ঞ সার্জন",
    titleEN: "Gynecology & Obstetrics Surgeon",
    qualificationsBD: "এমবিবিএস, গাইনী ও প্রসূতি বিদ্যায় বিশেষ অভিজ্ঞ",
    qualificationsEN: "MBBS, Advanced Gynecological Surgery Expertise",
    designationBD: "প্রসূতি ও স্ত্রীরোগ সার্জন, নিরাময় ক্লিনিক",
    designationEN: "Pregnancy & Obstetrics Specialist, Niramoy Clinic",
    scheduleBD: "প্রতি শনিবার: বিকাল ৩:০০টা – রাত ৮:০০টা",
    scheduleEN: "Every Saturday: 03:00 PM – 08:00 PM",
    daysBD: ["শনিবার"],
    daysEN: ["Saturday"],
    categories: ["gynecology"],
    phoneSerials: ["01717-975461", "01705-485643"],
    image: "placeholder",
    chamberBD: "নিরাময় ক্লিনিক এন্ড ডায়াগনোসিস, বিডিআর রোড, লালমনিরহাট",
    chamberEN: "Niramoy Clinic & Diagnosis, BDR Road, Lalmonirhat"
  },
  {
    id: "dr-madhabi-das",
    nameBD: "ডা. মাধবী দাস",
    nameEN: "Dr. Madhabi Das",
    titleBD: "গাইনী ও অবস বিশেষজ্ঞ",
    titleEN: "Gynecology & Obstetrics Specialist",
    qualificationsBD: "এমবিবিএস, প্রসূতি সেবা ও সাধারণ স্ত্রীরোগ বিশেষজ্ঞ",
    qualificationsEN: "MBBS, Maternity & Gynecological Practitioner",
    designationBD: "স্ত্রীরোগ ও প্রসূতি বিশেষজ্ঞ এবং সার্জন",
    designationEN: "Obs & Gynae Specialist Surgeon, Niramoy Clinic",
    scheduleBD: "প্রতি শনিবার: বিকাল ৩:০০টা – রাত ৮:০০টা",
    scheduleEN: "Every Saturday: 03:00 PM – 08:00 PM",
    daysBD: ["শনিবার"],
    daysEN: ["Saturday"],
    categories: ["gynecology"],
    phoneSerials: ["01717-975461", "01705-485643"],
    image: "placeholder",
    chamberBD: "নিরাময় ক্লিনিক এন্ড ডায়াগনোসিস, বিডিআর রোড, লালমনিরহাট",
    chamberEN: "Niramoy Clinic & Diagnosis, BDR Road, Lalmonirhat"
  },
  {
    id: "dr-nobiur-rahman",
    nameBD: "ডা. মোঃ নবিউর রহমান",
    nameEN: "Dr. Md. Nobiur Rahman",
    titleBD: "জেনারেল প্র্যাকটিশনার / সাধারণ চিকিৎসক",
    titleEN: "General Practitioner (GP)",
    qualificationsBD: "এমবিবিএস (মেডিসিন ও সাধারণ স্বাস্থ্য)",
    qualificationsEN: "MBBS (General Healthcare & Primary Care)",
    designationBD: "আবাসিক চিকিৎসক, নিরাময় ক্লিনিক সদর, লালমনিরহাট",
    designationEN: "Resident Physician, Niramoy Clinic, Lalmonirhat",
    scheduleBD: "প্রতিদিন: সকাল ১১:০০টা – দুপুর ২:০০টা এবং বিকাল ৪:০০টা – রাত ৮:০০টা (শুক্রবার বন্ধ)",
    scheduleEN: "Daily: 11:00 AM – 02:00 PM & 04:00 PM – 08:00 PM (Closed on Friday)",
    daysBD: ["শনিবার", "রবিবার", "সোমবার", "মঙ্গলবার", "বুধবার", "বৃহস্পতিবার"],
    daysEN: ["Saturday", "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday"],
    categories: ["general"],
    phoneSerials: ["01717-975461", "01705-485643"],
    image: "placeholder",
    chamberBD: "নিরাময় ক্লিনিক এন্ড ডায়াগনোসিস, বিডিআর রোড, লালমনিরহাট",
    chamberEN: "Niramoy Clinic & Diagnosis, BDR Road, Lalmonirhat"
  }
];

export const DIAGNOSTICS_DATA: Test[] = [
  {
    id: "cbc",
    nameEN: "Complete Blood Count (CBC) with ESR",
    nameBD: "সম্পূর্ণ রক্ত পরীক্ষা (সিবিসি + ইএসআর)",
    categoryEN: "Hematology",
    categoryBD: "রক্ত পরীক্ষা / হেমাটোলজি",
    preparationEN: "Fasting not strictly required. Best done on lightweight stomach.",
    preparationBD: "খালি পেটে থাকা বাধ্যতামূলক নয়। হালকা খাবার খেয়ে করা ভালো।",
    priceBD: "৪০০ ৳",
    popular: true
  },
  {
    id: "blood-sugar",
    nameEN: "Blood Glucose (FBS / RBS / 2HABF)",
    nameBD: "রক্তের সুগার টেস্ট (খালি পেটে / খাওয়ার পর)",
    categoryEN: "Biochemistry",
    categoryBD: "বায়োকেমিস্ট্রি পরীক্ষা",
    preparationEN: "FBS requires 8-10 hours fasting. RBS can be done anytime.",
    preparationBD: "FBS এর জন্য ৮-১০ ঘণ্টা খালি পেটে থাকতে হবে। RBS যেকোনো সময়ে সম্ভব।",
    priceBD: "১৫০ ৳",
    popular: true
  },
  {
    id: "hba1c",
    nameEN: "HbA1c (Average 3-Month Glucose)",
    nameBD: "এইচবিএ১সি (৩ মাসের গড় সুগার পরীক্ষা)",
    categoryEN: "Biochemistry",
    categoryBD: "বায়োকেমিস্ট্রি পরীক্ষা",
    preparationEN: "Fasting not required.",
    preparationBD: "খালি পেটে থাকার প্রয়োজন নেই।",
    priceBD: "৮০০ ৳",
    popular: false
  },
  {
    id: "lft",
    nameEN: "Liver Function Test (LFT)",
    nameBD: "লিভার ফাংশন টেস্ট (এলএফটি)",
    categoryEN: "Biochemistry",
    categoryBD: "বায়োকেমিস্ট্রি পরীক্ষা",
    preparationEN: "Fasting of 10-12 hours is recommended.",
    preparationBD: "১০-১২ ঘণ্টা খালি পেটে থাকার পরামর্শ দেওয়া হয়।",
    priceBD: "৯০০ ৳",
    popular: true
  },
  {
    id: "creatinine",
    nameEN: "Serum Creatinine",
    nameBD: "রক্তে ক্রিয়েটিনিন পরীক্ষা (কিডনি পরীক্ষা)",
    categoryEN: "Biochemistry",
    categoryBD: "বায়োকেমিস্ট্রি পরীক্ষা",
    preparationEN: "Fasting not required. Drink standard amount of water.",
    preparationBD: "খালি পেটে থাকার প্রয়োজন নেই। পরিমিত পানি পান করুন।",
    priceBD: "৩০০ ৳",
    popular: true
  },
  {
    id: "lipid",
    nameEN: "Lipid Profile (Cholesterol, TG, HDL, LDL)",
    nameBD: "লিপিড প্রোফাইল (কোলেস্টেরল ও চর্বি পরীক্ষা)",
    categoryEN: "Biochemistry",
    categoryBD: "বায়োকেমিস্ট্রি পরীক্ষা",
    preparationEN: "Strict fasting of 12 hours is mandatory.",
    preparationBD: "১২ ঘণ্টা সম্পূর্ণ খালি পেটে থাকতে হবে (শুধুমাত্র পানি খাওয়ার অনুমতি আছে)।",
    priceBD: "১০০০ ৳",
    popular: true
  },
  {
    id: "thyroid-tsh",
    nameEN: "Thyroid Function (TSH / FT4)",
    nameBD: "থাইরয়েড হরমোন পরীক্ষা (টিএসএইচ)",
    categoryEN: "Hormone Assay",
    categoryBD: "হরমোন ও ভাইরাস মার্কার",
    preparationEN: "Morning specimen is optimal. Fasting not mandatory.",
    preparationBD: "সকালের রক্ত নেওয়া সবচেয়ে ভালো। খালি পেটে থাকা জরুরি নয়।",
    priceBD: "৭০০ ৳",
    popular: true
  },
  {
    id: "urine-re",
    nameEN: "Urine Routine & Examination (R/E)",
    nameBD: "ইউরিন রুটিন পরীক্ষা (ইউরিন আর/ই)",
    categoryEN: "Urine & Stool",
    categoryBD: "ইউরিন ও মল পরীক্ষা",
    preparationEN: "Collect mid-stream morning urine specimen in clean container.",
    preparationBD: "সকালের প্রথম প্রস্রাবের মাঝের অংশ পরিষ্কার পাত্রে সংগ্রহ করুন।",
    priceBD: "২০০ ৳",
    popular: true
  },
  {
    id: "viral-hbsag",
    nameEN: "HBsAg Screening (Hepatitis B)",
    nameBD: "এইচবিএসএজি (হেপাটাইটিস বি স্ক্রিনিং)",
    categoryEN: "Viral Markers",
    categoryBD: "হরমোন ও ভাইরাস মার্কার",
    preparationEN: "No specific preparation or fasting required.",
    preparationBD: "নির্দিষ্ট কোনো প্রস্তুতির প্রয়োজন নেই।",
    priceBD: "৩৫০ ৳",
    popular: false
  },
  {
    id: "usg-pregnancy",
    nameEN: "Ultrasonography (USG of Pregnancy / Pelvis)",
    nameBD: "আল্ট্রাসনোগ্রাফি (গর্ভবতী মা / পেলভিস)",
    categoryEN: "Imaging",
    categoryBD: "ইমেজিং ও এক্স-রে",
    preparationEN: "Requires full bladder. Drink plenty of water 1 hour before.",
    preparationBD: "প্রস্রাবের তীব্র চাপ থাকতে হবে। পরীক্ষার ১ ঘণ্টা আগে প্রচুর পানি খান।",
    priceBD: "৮০০ ৳",
    popular: true
  },
  {
    id: "usg-abdomen",
    nameEN: "Ultrasonography of Whole Abdomen",
    nameBD: "ইউএসজি (সম্পূর্ণ পেট / হোল অ্যাবডোমেন)",
    categoryEN: "Imaging",
    categoryBD: "ইমেজিং ও এক্স-রে",
    preparationEN: "Strict fasting of 6-8 hours. Drink water to keep bladder full if needed.",
    preparationBD: "৬-৮ ঘণ্টা একদম খালি পেটে থাকতে হবে। প্রয়োজন অনুসারে পানি খেয়ে প্রস্রাব চেপে রাখুন।",
    priceBD: "১২০০ ৳",
    popular: true
  },
  {
    id: "dg-xray",
    nameEN: "Digital X-Ray (Chest / Spine)",
    nameBD: "ডিজিটাল এক্স-রে (বুক / কোমর)",
    categoryEN: "Imaging",
    categoryBD: "ইমেজিং ও এক্স-রে",
    preparationEN: "Requires removal of metal jewelry and change into gown.",
    preparationBD: "ধাতব অলংকার পরিধান করা যাবে না। পরীক্ষা করার সময় মেটাল পরিহার্য।",
    priceBD: "৪০০ ৳",
    popular: true
  },
  {
    id: "ecg-12",
    nameEN: "ECG (12 Channels / Digital)",
    nameBD: "ইসিজি (ডিজিটাল ১২ চ্যানেল)",
    categoryEN: "Imaging",
    categoryBD: "ইমেজিং ও এক্স-রে",
    preparationEN: "Keep chest area accessible, relax while testing.",
    preparationBD: "পরীক্ষার সময় বুক হালকা রাখতে হবে, সম্পূর্ণ রিল্যাক্স থাকুন।",
    priceBD: "৩০০ ৳",
    popular: true
  }
];
export const EMERGENCY_PHONES = [
  "+8801797-975461",
  "+8801705-485643"
];

export const OFFICE_ADDRESS = {
  BD: "খোর্দ্দ সাপটানা, বিডিআর রোড (পৌরসভা ভবনের উত্তর পাশে), লালমনিরহাট সদর।",
  EN: "Khordda Sapatana, BDR Road (North of Pourashava Building), Lalmonirhat Sadar."
};
export const OT_SERVICES_BD = [
  {
    title: "জেনারেল সার্জারি (General Surgery)",
    desc: "অ্যাপেন্ডিসাইটিস, হার্নিয়া, হাইড্রোসিল, গলব্লাডারস্টোন ও যেকোনো প্রকার টিউমার অপারেশন ল্যাপারোস্কপিক ও ওপেন পদ্ধতিতে করা হয়।",
    surgeon: "ডা. মোঃ শরীফুল ইসলাম (ননতু) ও বিশেষজ্ঞ দল"
  },
  {
    title: "সিজারিয়ান সেকশন ও স্ত্রীরোগ অপারেশন (C-Section & Gynae OT)",
    desc: "জরুরি ও সিডিউলড প্রসূতি সিজার, জরায়ু টিউমার এবং গাইনী সমস্যার আধুনিক ও ব্যথামুক্ত অপারেশন থিয়েটার সুবিধা।",
    surgeon: "ডা. নভেরা ইসলাম, ডা. ইশরাত জাহান লোপা ও বিশেষজ্ঞ গাইনী টিম"
  },
  {
    title: "অর্থোপেডিকস সার্জারি (Orthopedic Surgery)",
    desc: "হাড় ভাঙা, জোড়া লাগানো, প্লাস্টার এবং উন্নত হাড়-জোড় ও ট্রমা চিকিৎসা সুবিধা সম্পন্ন আধুনিক অপারেশন থিয়েটার।",
    surgeon: "সহযোগী অধ্যাপক ডা. এম.এম. হক (মাহফিল) ও ডা. নাহিদ বাদশা"
  }
];
export const OT_SERVICES_EN = [
  {
    title: "General & Laparoscopic Surgery",
    desc: "Appendix, Hernia, Hydrocele, Gallbladder stones, and tumors removed via state-of-the-art open or laparoscopic (keyhole) procedures.",
    surgeon: "Dr. Shariful Islam Nontu, Dr. Md. Abdul Jabbar & Team"
  },
  {
    title: "Maternity & C-Section",
    desc: "24/7 Caesarean deliveries, ovarian cystectomies, and core gynecological operations in fully sterilized setups.",
    surgeon: "Dr. Novera Islam, Dr. Israt Jahan Lopa, Dr. Iffat Abdullah & Team"
  },
  {
    title: "Orthopedic & Trauma Surgery",
    desc: "Bone fractures repair, joint surgery, splints, and comprehensive pediatric/adult corrective trauma treatments.",
    surgeon: "Assoc. Prof. Dr. M.M. Haq (Mahfil), Dr. Nahid Badsha & Team"
  }
];
